image: gcc
variables:
  GIT_SUBMODULE_STRATEGY: normal
  
stages:
  - build
  - doc
  - test

before_script:
  - git status
  - mkdir -p build/
  - cd build/
  - mcstas-2.6-environment
  
compile:
  stage: build
  script:
    - cd ..
    - cd openPMD-api
    - patch -p1 < ../cmake_api.patch
    - cd ../build/
    - cmake .. -DopenPMD_USE_PYTHON=OFF -DopenPMD_INSTALL=OFF -DopenPMD_USE_INTERNAL_CATCH=ON -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_CLI_TOOLS=ON -DopenPMD_USE_MPI=OFF
    - cmake --build .

test:
  stage: test
  script:
   - ctest --verbose -R mid
   
pages:
  stage: doc
  script:
    - cmake --build . --target doc
    - mv doc/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master